title: 默默的伟哥
description: 老司机的日记
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile
locale: "zh-CN"
url: "http://aiyd.me"

author:
  name: "默默的伟哥"
  avatar: "/assets/images/bio-photo.jpg"

