title: 默默的伟哥
description: 老码农的mark
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
locale: "zh-CN"
url: "http://aiyd.me"

author:
  name   : "默默的伟哥"
  avatar : "/assets/images/bio-photo.jpg"

gems:
  - jekyll-mentions
